import { Project, SyntaxKind } from 'ts-morph';
import type { ChallengeHint } from './types.ts';

/**
 * Deterministic documentation hints (docs/design-v1.md §6.2, source
 * 'documentation'). Nothing here is generated by an LLM and no implementation
 * code is ever included: hints are built purely from the target function's
 * JSDoc text and its parameter names.
 *
 * - Level 1: the summary sentence (first sentence of the first JSDoc paragraph).
 * - Level 2: follow-up points (the rest of the first paragraph, the second
 *   paragraph, and an `@remarks` tag when present).
 * - Level 3: a usage reminder listing the parameter names.
 *
 * When a piece of material is missing the remaining pieces are downgraded by
 * one level, so published levels are always contiguous starting at 1. The
 * result is truncated to `maxLevel`.
 */
export function documentationHints(sourceText: string, targetExport: string, maxLevel: 1 | 2 | 3): ChallengeHint[] {
  const pieces = hintPieces(sourceText, targetExport);
  return pieces
    .slice(0, maxLevel)
    .map((text, index): ChallengeHint => ({ level: (index + 1) as 1 | 2 | 3, text, source: 'documentation' }));
}

/** Returns the ordered hint ingredients (empty strings are dropped). */
function hintPieces(sourceText: string, targetExport: string): string[] {
  const project = new Project({ useInMemoryFileSystem: true });
  const sourceFile = project.createSourceFile('/hints.ts', sourceText, { overwrite: true });
  const fn = sourceFile.getFunction(targetExport);

  const pieces: string[] = [];
  if (!fn) {
    return pieces;
  }

  // The effective JSDoc is the one directly preceding the declaration; stray
  // comment blocks earlier in the leading trivia (e.g. commented-out code) are
  // attached as earlier entries, so use the last one.
  const jsDocs = fn.getJsDocs();
  const jsDoc = jsDocs[jsDocs.length - 1];
  const description = jsDoc ? cleanDocText(jsDoc.getDescription()) : '';
  const [summary, followUp] = splitSummary(description);
  if (summary) {
    pieces.push(summary);
  }

  let remarks = '';
  if (jsDoc) {
    for (const tag of jsDoc.getTags()) {
      if (tag.getTagName().toLowerCase() === 'remarks') {
        remarks = cleanDocText(tag.getCommentText() ?? '');
        break;
      }
    }
  }
  const details = [followUp, remarks].filter((part) => part.length > 0).join(' ').trim();
  if (details) {
    pieces.push(details);
  }

  const paramNames = parameterNamesOf(fn);
  if (paramNames.length > 0) {
    pieces.push(
      `Consider each parameter in turn (${paramNames.join(', ')}), including missing, empty and boundary values.`
    );
  }

  return pieces;
}

function parameterNamesOf(fn: import('ts-morph').FunctionDeclaration): string[] {
  const names: string[] = [];
  for (const param of fn.getParameters()) {
    const nameNode = param.getNameNode();
    if (nameNode.isKind(SyntaxKind.Identifier)) {
      names.push(nameNode.getText());
    } else {
      const text = nameNode.getText().replace(/\s+/g, ' ').trim();
      if (text.length > 0) {
        names.push(text);
      }
    }
  }
  return names;
}

/** Normalizes whitespace and removes fenced code blocks so hints never carry implementation code. */
function cleanDocText(raw: string): string {
  const withoutFences = raw.replace(/```[\s\S]*?```/g, ' ');
  return withoutFences.replace(/\s+/g, ' ').trim();
}

/** Splits a description into the summary sentence and the remaining text. */
function splitSummary(description: string): [string, string] {
  const match = /^(.+?[.!?])(?:\s|$)/u.exec(description);
  if (!match) {
    return [description, ''];
  }
  return [match[1].trim(), description.slice(match[0].length).trim()];
}
