// Structured run protocol shared between the parent application and the
// sandboxed runner.
//
// The sandbox (a code string generated by `bootstrap.ts`) posts a single
// `result` message back to the parent via `parent.postMessage`. The parent
// combines it with compile/error signals from the Sandpack bundler and its own
// timeout bookkeeping into a `TestRunResult`.
//
// These types and predicates are pure so they can be unit-tested in Node
// without a browser or a live sandbox.

export const RUNNER_MESSAGE_SOURCE = 'lodash-challenge-runner';
export const RUNNER_MESSAGE_VERSION = 1;

export type ConsoleMethod = 'log' | 'info' | 'warn' | 'error' | 'debug';

export interface ConsoleEntry {
  method: ConsoleMethod;
  args: string[];
}

export interface TestCaseResult {
  suite: string;
  name: string;
  status: 'passed' | 'failed' | 'skipped';
  error?: string;
}

export type SandboxRunStatus = 'passed' | 'failed' | 'runtime-error';

export type RunStatus = SandboxRunStatus | 'timeout' | 'compile-error';

export interface TestRunResult {
  runId: string;
  status: RunStatus;
  durationMs: number;
  tests: TestCaseResult[];
  console: ConsoleEntry[];
  error?: string;
}

export interface RunnerResultMessage {
  source: typeof RUNNER_MESSAGE_SOURCE;
  version: number;
  runId: string;
  type: 'result';
  payload: {
    status: SandboxRunStatus;
    tests: TestCaseResult[];
    console: ConsoleEntry[];
    error?: string;
  };
}

const CONSOLE_METHODS: ReadonlySet<string> = new Set(['log', 'info', 'warn', 'error', 'debug']);
const TEST_STATUSES: ReadonlySet<string> = new Set(['passed', 'failed', 'skipped']);
const SANDBOX_STATUSES: ReadonlySet<string> = new Set(['passed', 'failed', 'runtime-error']);

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isTestCaseResult(value: unknown): value is TestCaseResult {
  return (
    isRecord(value) &&
    typeof value.suite === 'string' &&
    typeof value.name === 'string' &&
    typeof value.status === 'string' &&
    TEST_STATUSES.has(value.status) &&
    (value.error === undefined || typeof value.error === 'string')
  );
}

function isConsoleEntry(value: unknown): value is ConsoleEntry {
  return (
    isRecord(value) &&
    typeof value.method === 'string' &&
    CONSOLE_METHODS.has(value.method) &&
    Array.isArray(value.args) &&
    value.args.every((arg) => typeof arg === 'string')
  );
}

/** Returns true when `data` is a well-formed result message from the sandbox. */
export function isRunnerResultMessage(data: unknown): data is RunnerResultMessage {
  if (!isRecord(data)) {
    return false;
  }
  if (data.source !== RUNNER_MESSAGE_SOURCE || data.type !== 'result') {
    return false;
  }
  if (data.version !== RUNNER_MESSAGE_VERSION) {
    return false;
  }
  if (typeof data.runId !== 'string' || data.runId.length === 0) {
    return false;
  }
  const payload = data.payload;
  if (!isRecord(payload)) {
    return false;
  }
  if (typeof payload.status !== 'string' || !SANDBOX_STATUSES.has(payload.status)) {
    return false;
  }
  if (!Array.isArray(payload.tests) || !payload.tests.every(isTestCaseResult)) {
    return false;
  }
  if (!Array.isArray(payload.console) || !payload.console.every(isConsoleEntry)) {
    return false;
  }
  if (payload.error !== undefined && typeof payload.error !== 'string') {
    return false;
  }
  return true;
}

export interface TestSummary {
  total: number;
  passed: number;
  failed: number;
  skipped: number;
  failures: Array<{ name: string; error?: string }>;
}

/** Summarizes raw test case results into counts (pure). */
export function summarizeTests(results: readonly TestCaseResult[]): TestSummary {
  let passed = 0;
  let failed = 0;
  let skipped = 0;
  const failures: Array<{ name: string; error?: string }> = [];
  for (const result of results) {
    if (result.status === 'passed') {
      passed += 1;
    } else if (result.status === 'skipped') {
      skipped += 1;
    } else {
      failed += 1;
      failures.push({ name: result.name, error: result.error });
    }
  }
  return { total: results.length, passed, failed, skipped, failures };
}

/** Derives the sandbox-reported run status from raw test results (pure). */
export function statusFromTests(results: readonly TestCaseResult[]): 'passed' | 'failed' {
  const summary = summarizeTests(results);
  return summary.failed > 0 ? 'failed' : 'passed';
}
